"""empty message

Revision ID: 7bd9423d6eb8
Revises: 4fb86c9b994d
Create Date: 2023-10-15 03:52:34.082253

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7bd9423d6eb8'
down_revision = '4fb86c9b994d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
