"""empty message

Revision ID: 8f3c4a9e6ac3
Revises: 9fa85cd6d2ad
Create Date: 2023-10-15 05:34:43.277598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f3c4a9e6ac3'
down_revision = '9fa85cd6d2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=mysql.VARCHAR(length=3000),
               type_=sa.Text(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.Text(length=3000),
               type_=mysql.VARCHAR(length=3000),
               existing_nullable=True)

    # ### end Alembic commands ###
