"""empty message

Revision ID: 974a01b4444a
Revises: 1195792e70d3
Create Date: 2023-10-14 18:19:42.394235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '974a01b4444a'
down_revision = '1195792e70d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.alter_column('avg_price',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.drop_index('ix_restaurant_categories')
        batch_op.drop_index('ix_restaurant_cuisines')
        batch_op.drop_column('cuisines')
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('cuisines', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_restaurant_cuisines', ['cuisines'], unique=False)
        batch_op.create_index('ix_restaurant_categories', ['categories'], unique=False)
        batch_op.alter_column('avg_price',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
