"""empty message

Revision ID: 9fa85cd6d2ad
Revises: aa90e4d402ea
Create Date: 2023-10-15 05:23:53.592424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa85cd6d2ad'
down_revision = 'aa90e4d402ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hashtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hashtag_content'), ['content'], unique=False)

    op.create_table('post_hashtag',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('hashtag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hashtag_id'], ['hashtag.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], )
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['sponsor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sponsor_id')

    op.drop_table('post_hashtag')
    with op.batch_alter_table('hashtag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hashtag_content'))

    op.drop_table('hashtag')
    # ### end Alembic commands ###
